// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Main entry point of the API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Welcome"
                ],
                "summary": "Index Page",
                "responses": {
                    "200": {
                        "description": "Returns welcome message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Endpoint to check the health status of the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "Returns service health status",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/hello/:name": {
            "get": {
                "description": "Endpoint to Welcome user and say Hello \"Name\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Welcome"
                ],
                "summary": "Hello User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name in the URL param",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Request Error or parameter missing",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "When user not found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Simple ping-pong endpoint to check if the server is running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Ping Endpoint",
                "responses": {
                    "200": {
                        "description": "Returns pong response",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "golang-vercel.vercel.app",
	BasePath:         "",
	Schemes:          []string{"https", "http"},
	Title:            "Golang Vercel Deployment",
	Description:      "API Documentation for Golang deployment in vercel serverless environment",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
